# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties


mod_name=No Zombie Villagers
mod_id=nozombievillagers
mod_group_id=com.mactso.nozombievillagers
mod_version=0.2.0
minecraft_version=1.21.6
forge_version=56.0.9


mapping_channel=official
mapping_version=1.21.6

minecraft_version_range=[1.21.6,1.22)
mod_authors=MacTso, Lupicus