modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
[[mods]]
modId="nozombievillagers"
version="${file.jarVersion}"
displayName="No Zombie Villagers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/no-zombie-villagers"
updateJSONURL="https://github.com/mactso/NoZombieVillagers/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='nozombievillagers.'
[[dependencies.nozombievillagers]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.nozombievillagers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="SERVER"
